package com.myspace.retail_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Shelve")
public class Shelve implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label(value = "Shelve Item")
	private java.lang.String shelveItem;

	public Shelve() {
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getShelveItem() {
		return this.shelveItem;
	}

	public void setShelveItem(java.lang.String shelveItem) {
		this.shelveItem = shelveItem;
	}

	public Shelve(java.lang.String category, java.lang.String shelveItem) {
		this.category = category;
		this.shelveItem = shelveItem;
	}

}